### ISSUE TITLE
Problems setting up Pipeline

### ISSUE THREAD

**Issue by alex-seitz** [imgag/megSAP#32] opened 2019-07-18 07:13 UTC
Hey,
The current version of R in the apt repositories of Ubuntu server 18.04 is 3.4.X. However, clinCNV needs at least 3.5. So you will need to add the corresponding repository by hand. A hint in the installation documentation would be great, as they specifically refer Ubuntu 18.04.

Additionally, when running ClinCNV I get the error
`Fatal error: cannot open file '/opt/megSAP//data/tools/ClinCNV-1.15.0//clinCNV.R': No such file or directory`
When looking at the installed programs, the current download_tools.sh downloads the version 1.16.0
Thus you probably need to adapt this in your settings.ini

Furthermore, I had to manually install the package R.utils `install.packages("R.utils")`

I currently have only tried to run clinCNV separately. The rest of the pipeline will follow in time.

I will start to set up the pipeline again from scratch on a fresh install of ubuntu server 18.04 within the next few weeks and will let you know if I run into additional problems

Best,
Alex

**Comment by marc-sturm** [comment] 2019-07-18 11:07
Hi Alex,

thanks for your feedback.

1) R version
We run ClinCNV under Ubuntu 18.04 with R 3.4:
> >cat /etc/issue
> Ubuntu 18.04.2 LTS \n \l
>
>>Rscript --version
> R scripting front-end version 3.4.4 (2018-03-15)

Why do you think it requires R 3.5?
Perhaps the missing utils is related to this issue...

2) clinCNV version
I updated the default settings INI file with this commit: e951bf9047598e7283079b64940161419e2a6b87
Can you verify that it works now?

Best,
  Marc

**Comment by alex-seitz** [comment] 2019-07-18 11:12
Hi Marc,
it was one of the packages that have to be installed for ClinCNV. I'm not 100% sure, but I think it was the package "mclust" which again has a subpackage which is now only available on R>3.5
I'm on vacation next week but will then set up the complete pipeline again on a fresh install of Ubuntu 18.04. I will document any problems and let you know.

FYI: We will meet on the 8th of August in Tübingen either way.

Best,
Alex

**Comment by marc-sturm** [comment] 2019-07-18 11:24
Ok, I will also check on a VM and close the issue for now.

Nope, your visit was moved to 7th or August :)

Best,
  Marc

**Comment by alex-seitz** [comment] 2019-07-18 11:57
Ok

**Comment by alex-seitz** [comment] 2019-08-13 12:47
Hey Marc,
after the reinstallation, everything until ClinCNV seems to be running.
There it says it can't install the package `party`. When trying to manually install it, it fails with on several packages, one of them being `mvtnorm`
The [official documentation](https://cran.r-project.org/web/packages/mvtnorm/index.html) of the packages says it needs R>3.5.0 (see problem above)

I will now try to install the newest version of R and try to reinstall ClinCNV

Best,
Alex

**Comment by alex-seitz** [comment] 2019-08-13 14:27
Hey,
after updating to the latest version of R described [here ](https://linuxize.com/post/how-to-install-r-on-ubuntu-18-04/) and recompiling all R packages with the command `update.packages(ask=FALSE, checkBuilt=TRUE)` I could sucessfully install the dependencies for `clinCNV` and run the CNV analysis

Best,
Alex

**Comment by marc-sturm** [comment] 2019-08-13 15:25
Hi Alex,

good that you could solve it simply by upgrading.

I cannot reproduce the problem here we use Ubuntu 18.04 and R 3.4.4:
When I install `party` it works:
R> install.packages("party", repos="https://cran.rstudio.com")
Somehow `mvtnorm` is already installed, so it must have been available somewhen for R 3.4.4.

German will try to make a Bioconda recipe to install ClinCNV more smoothly.

Best,
  Marc

**Closed by marc-sturm** 2019-08-13 15:25 UTC
